import type { NicheId, Source } from "./types";

export const RELATION_FORUMS: Source[] = [
  {
    id: "woman-forum",
    name: "Woman.ru — форум «Отношения»",
    short: "Woman.ru",
    region: "RU",
    country: "Россия",
    language: "ru",
    rss: "https://www.woman.ru/forum_recent_sitemap.xml",
    site: "https://www.woman.ru/relations/forum/?sort=new",
    affiliation: "independent",
    biasNote: "Крупнейший женский форум РФ: муж, жена, измены, границы, семья.",
    niches: ["relations"],
    listKind: "sitemap",
    keepPath: "/relations/",
  },
  {
    id: "umama-love",
    name: "U-mama — Любовь и секс",
    short: "U-mama",
    region: "RU",
    country: "Россия",
    language: "ru",
    rss: "https://www.u-mama.ru/forum/family/love-and-sex/",
    site: "https://www.u-mama.ru/forum/family/love-and-sex/",
    affiliation: "independent",
    biasNote: "Женский форум мам: измены, знакомства 40+, сила на отношения.",
    niches: ["relations"],
    listKind: "html",
    hrefPattern: "/forum/family/love-and-sex/\\d+",
  },
  {
    id: "umama-family",
    name: "U-mama — Семейные отношения",
    short: "U-mama семья",
    region: "RU",
    country: "Россия",
    language: "ru",
    rss: "https://www.u-mama.ru/topics/family/family-relationships/",
    site: "https://www.u-mama.ru/topics/family/family-relationships/",
    affiliation: "independent",
    biasNote: "Быт пары, свекрови, роли в доме, самостоятельные мамы.",
    niches: ["relations"],
    listKind: "html",
    hrefPattern: "/forum/family/[^\"']+/\\d+",
  },
  {
    id: "baby-forum",
    name: "Baby.ru — форум",
    short: "Baby.ru",
    region: "RU",
    country: "Россия",
    language: "ru",
    rss: "https://forum.baby.ru/popular/",
    site: "https://forum.baby.ru/",
    affiliation: "independent",
    biasNote: "Мамы: беременность, пара после родов, распределение ролей.",
    niches: ["relations", "health"],
    listKind: "html",
    hrefPattern: "/(?:community|answers|topic|thread)/[^\"']+",
  },
  {
    id: "babyblog",
    name: "Babyblog — семья",
    short: "Babyblog",
    region: "RU",
    country: "Россия",
    language: "ru",
    rss: "https://www.babyblog.ru/community",
    site: "https://www.babyblog.ru/community/used/semya",
    affiliation: "independent",
    biasNote: "Женские сообщества: семейная психология и интимные отношения.",
    niches: ["relations"],
    listKind: "html",
    hrefPattern: "/communit(?:y|ies)/[^\"']+",
  },
  {
    id: "reddit-rel",
    name: "Reddit r/relationships",
    short: "r/rel",
    region: "US",
    country: "США",
    language: "en",
    rss: "https://old.reddit.com/r/relationships/.rss",
    site: "https://www.reddit.com/r/relationships/",
    affiliation: "independent",
    biasNote: "Живые кейсы пар. Много женских историй про доверие и уход.",
    niches: ["relations"],
  },
  {
    id: "reddit-advice",
    name: "Reddit r/relationship_advice",
    short: "r/advice",
    region: "US",
    country: "США",
    language: "en",
    rss: "https://old.reddit.com/r/relationship_advice/.rss",
    site: "https://www.reddit.com/r/relationship_advice/",
    affiliation: "independent",
    biasNote: "Советы по кризисам: разговор, границы, расставание.",
    niches: ["relations"],
  },
  {
    id: "twox",
    name: "Reddit r/TwoXChromosomes",
    short: "TwoX",
    region: "US",
    country: "США",
    language: "en",
    rss: "https://old.reddit.com/r/TwoXChromosomes/.rss",
    site: "https://www.reddit.com/r/TwoXChromosomes/",
    affiliation: "independent",
    biasNote: "Женская комната: тело, безопасность, отношения, работа.",
    niches: ["relations", "health"],
  },
  {
    id: "askwomen",
    name: "Reddit r/AskWomen",
    short: "AskWomen",
    region: "US",
    country: "США",
    language: "en",
    rss: "https://old.reddit.com/r/AskWomen/.rss",
    site: "https://www.reddit.com/r/AskWomen/",
    affiliation: "independent",
    biasNote: "Женщины отвечают женщинам: свидания, брак, дружба, секс.",
    niches: ["relations"],
  },
  {
    id: "mumsnet",
    name: "Mumsnet Talk — Relationships",
    short: "Mumsnet",
    region: "US",
    country: "Великобритания",
    language: "en",
    rss: "https://www.mumsnet.com/talk/relationships",
    site: "https://www.mumsnet.com/talk/relationships",
    affiliation: "independent",
    biasNote: "Британский женский форум: брак, свекрови, секс, деньги пары.",
    niches: ["relations"],
    listKind: "html",
    hrefPattern: "/talk/relationships/\\d+-[^\"']+",
  },
];

export const FORUM_NICHES: NicheId[] = ["relations"];
