import type { Source } from "./types";

export const SOURCES: Source[] = [
  {
    id: "npr",
    name: "NPR News",
    short: "NPR",
    region: "US",
    country: "США",
    language: "en",
    rss: "https://feeds.npr.org/1001/rss.xml",
    site: "https://www.npr.org",
    affiliation: "public",
    biasNote: "Общественное вещание США. Сильная внутренняя повестка, мягкая подача.",
    niches: ["news", "health", "innovation"],
  },
  {
    id: "cnn",
    name: "CNN World",
    short: "CNN",
    region: "US",
    country: "США",
    language: "en",
    rss: "http://rss.cnn.com/rss/cnn_topstories.rss",
    site: "https://www.cnn.com",
    affiliation: "independent",
    biasNote: "Глобальная телесеть. Высокая скорость, акцент на кризис и картинку.",
    niches: ["news", "money", "health"],
  },
  {
    id: "techcrunch",
    name: "TechCrunch",
    short: "TC",
    region: "US",
    country: "США",
    language: "en",
    rss: "https://techcrunch.com/feed/",
    site: "https://techcrunch.com",
    affiliation: "independent",
    biasNote: "Стартапы и капитал Кремниевой долины. Инновации через призму рынка.",
    niches: ["innovation", "money"],
  },
  {
    id: "yonhap",
    name: "Yonhap News",
    short: "Yonhap",
    region: "KR",
    country: "Корея",
    language: "en",
    rss: "https://en.yna.co.kr/RSS/news.xml",
    site: "https://en.yna.co.kr",
    affiliation: "agency",
    biasNote: "Национальное агентство Кореи. КНДР, полупроводники, культура K.",
    niches: ["news", "innovation", "money"],
  },
  {
    id: "nhk",
    name: "NHK News",
    short: "NHK",
    region: "JP",
    country: "Япония",
    language: "ja",
    rss: "https://www.nhk.or.jp/rss/news/cat0.xml",
    site: "https://www.nhk.or.jp",
    affiliation: "public",
    biasNote: "Общественный вещатель Японии. Дисциплина факта, внутренний ритм архипелага.",
    niches: ["news", "health", "innovation"],
  },
  {
    id: "cgtn",
    name: "CGTN World",
    short: "CGTN",
    region: "CN",
    country: "Китай",
    language: "en",
    rss: "https://www.cgtn.com/subscribe/rss/section/world.xml",
    site: "https://www.cgtn.com",
    affiliation: "state",
    biasNote: "Госвещание КНР на английском. Сверять нарратив с независимыми лентами.",
    niches: ["news", "innovation", "money"],
  },
  {
    id: "tass",
    name: "ТАСС",
    short: "ТАСС",
    region: "RU",
    country: "Россия",
    language: "ru",
    rss: "https://tass.ru/rss/v2.xml",
    site: "https://tass.ru",
    affiliation: "agency",
    biasNote: "Государственное информагентство. Официальная рамка событий.",
    niches: ["news", "money"],
  },
  {
    id: "ria",
    name: "РИА Новости",
    short: "РИА",
    region: "RU",
    country: "Россия",
    language: "ru",
    rss: "https://ria.ru/export/rss2/archive/index.xml",
    site: "https://ria.ru",
    affiliation: "agency",
    biasNote: "Крупная русскоязычная лента. Высокий объём, широкая тематика.",
    niches: ["news", "health", "money"],
  },
  {
    id: "interfax",
    name: "Интерфакс",
    short: "Interfax",
    region: "RU",
    country: "Россия",
    language: "ru",
    rss: "https://www.interfax.ru/rss.asp",
    site: "https://www.interfax.ru",
    affiliation: "agency",
    biasNote: "Агентство с упором на экономику, рынки и официальные сообщения.",
    niches: ["money", "news", "innovation"],
  },
  {
    id: "lenta",
    name: "Лента.ру",
    short: "Lenta",
    region: "RU",
    country: "Россия",
    language: "ru",
    rss: "https://lenta.ru/rss",
    site: "https://lenta.ru",
    affiliation: "independent",
    biasNote: "Массовый агрегатор-издание. Быстрый пульс и широкий охват ниш.",
    niches: ["news", "relations", "health", "spirit", "money"],
  },
];

export const SOURCE_BY_ID = Object.fromEntries(
  SOURCES.map((source) => [source.id, source]),
) as Record<Source["id"], Source>;
